# Define any custom values for the base Helm chart here!
base: {}

# Define any custom values for the control place Helm chart here!
istiod: {}

# Define any custom values for the control place Helm chart here!
kiali: {}